# y = 1.5 + 0.5*x1 + 0.8*x2 - 0.2*x3

In [23]:
from numpy.linalg import inv
from numpy import dot
import pandas
import numpy as np

In [27]:
filedata = pandas.read_csv('./data.csv')
Xdata = np.array(filedata)
print(Xdata)

[[ 4.  10.  24.   6.7]
 [10.  14.  26.  12.5]
 [ 3.  19.  25.  13.2]
 [10.  14.  20.  13.7]
 [ 3.  13.  22.   9. ]
 [ 5.  11.  30.   6.8]
 [10.  12.  27.  10.7]
 [ 4.  16.  22.  11.9]
 [ 6.  17.  28.  12.5]
 [ 7.  18.  23.  14.8]
 [ 7.  13.  28.   9.8]
 [ 8.  14.  28.  11.1]
 [ 3.  14.  21.  10. ]
 [10.  14.  27.  12.3]
 [ 5.  15.  22.  11.6]
 [10.  15.  28.  12.9]
 [ 5.  11.  27.   7.4]]


In [28]:
X1 = Xdata[:,[0,1,2]]
y = Xdata[:,3]
m,n = X1.shape
b = np.ones(m)
X = np.c_[b,X1]
X

array([[ 1.,  4., 10., 24.],
       [ 1., 10., 14., 26.],
       [ 1.,  3., 19., 25.],
       [ 1., 10., 14., 20.],
       [ 1.,  3., 13., 22.],
       [ 1.,  5., 11., 30.],
       [ 1., 10., 12., 27.],
       [ 1.,  4., 16., 22.],
       [ 1.,  6., 17., 28.],
       [ 1.,  7., 18., 23.],
       [ 1.,  7., 13., 28.],
       [ 1.,  8., 14., 28.],
       [ 1.,  3., 14., 21.],
       [ 1., 10., 14., 27.],
       [ 1.,  5., 15., 22.],
       [ 1., 10., 15., 28.],
       [ 1.,  5., 11., 27.]])

In [29]:
a = dot(dot(inv(dot(X.T,X)),X.T),y)
a

array([ 1.5,  0.5,  0.8, -0.2])